version: "3"
services:
  sensor-listener:
    restart: always
    build:
      context: .
      dockerfile: sensor-listener/sensor-listener.dockerfile
    volumes:
      - /usr/src/app/node_modules
      - ./sensor-listener:/usr/src/app
      - ./config:/usr/src/config
    depends_on:
      - influxdb
  weather-station:
    restart: always
    build:
      dockerfile: weather-station/weather-station.dockerfile
      context: .
    volumes:
      - /usr/src/app/node_modules #bookmark volume (i.e. do NOT map to volume)
      - ./weather-station:/usr/src/app
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      WEATHER_API_LATITUDE: ${WEATHER_API_LATITUDE}
      WEATHER_API_LONGITUDE: ${WEATHER_API_LONGITUDE}
    depends_on:
      - influxdb
  sensor-alerts:
    restart: always
    build:
      context: .
      dockerfile: sensor-alerts/sensor-alerts.dockerfile
    volumes:
      - /usr/src/app/node_modules #bookmark volume (i.e. do NOT map to volume)
      - ./sensor-alerts:/usr/src/app
    environment:
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
  influxdb:
    image: influxdb:1.8  # or influxdb:2.7 if you're using v2
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
  redis:
    image: redis
    volumes:
      - ./data/redis:/var/lib/redis
  grafana:
    build:
      dockerfile: grafana.dockerfile
      context: ./grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel
    ports:
      - "3000:3000"  
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - influxdb
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
      - "8090:8090"
  telegraf:
    build:
      dockerfile: health-checks.Dockerfile
      context: ./health-checks
    environment:
      - HOST_PROC=/proc
