{
 "title": "Jannali home sensors dash",
 "time": { "from": "now-16h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature_data_in_celcius",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "study_room" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "temperature_data_in_celcius",
     "query": "SELECT min(\"temperature\") FROM \"temperature_data_in_celcius\" WHERE $timeFilter and \"temperature\" > 20 GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "temperature_data_in_celcius",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "study_room" }
     ]
    }
   ]
  },
  {
   "title": "Last temperature time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "format": "dateTimeAsUS",
   "valueName": "last_time",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "temperature_data_in_celcius",
     "query": "SELECT last(\"temperature\") FROM \"temperature_data_in_celcius\" WHERE (\"location\" = 'study_room') AND $timeFilter",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "study_room" }
     ]
    }
   ]
  },
  {
   "title": "Min time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "format": "dateTimeAsUS",
   "valueName": "last_time",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature_data_in_celcius",
     "query": "SELECT min(\"temperature\") FROM \"temperature_data_in_celcius\" WHERE (\"location\" = 'study_room' AND \"temperature\" > 20) AND $timeFilter\n\n",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "study_room" }
     ]
    }
   ]
  },
  {
   "title": "Max time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 7 },
   "format": "dateTimeAsUS",
   "valueName": "last_time",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "temperature_data_in_celcius",
     "query": "SELECT max(\"temperature\") FROM \"temperature_data_in_celcius\" WHERE (\"location\" = 'study_room') AND $timeFilter\n",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "study_room" }
     ]
    }
   ]
  },
  {
   "title": "Room temperature in study room",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature_data_in_celcius",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "study_room" }
     ]
    }
   ]
  }
 ]
}