name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [sensor-listener, sensor-alerts, weather-station]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ${{ matrix.dir }}/package-lock.json
      - name: Install dependencies
        working-directory: ${{ matrix.dir }}
        run: npm ci
      - name: Run tests
        working-directory: ${{ matrix.dir }}
        run: npm test

  home-automation-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install pytest
        run: pip install pytest
      - name: Run pytest
        working-directory: home-automation
        run: pytest
